### ISSUE TITLE
Padding issues in the image box

### ISSUE THREAD

**Issue by kunaljain0212** [PragatiVerma18/Snappify#1]
The screenshot is not displayed completely since there are padding issues in the box that displays the screenshot. 
I am attaching a screenshot of the same below:

![image](https://user-images.githubusercontent.com/56078934/100526183-8c405000-31ec-11eb-839f-116205152507.png)

### **We can see that the webpage is not scrollable anymore.**

**Comment by kunaljain0212** [comment]
Can I work on this please @PragatiVerma18 ?

**Comment by PragatiVerma18** [comment]
Go ahead @kunaljain0212!

**Comment by kunaljain0212** [comment]
I have created a pull request for this issue #3 it is ready for review :)
