### ISSUE TITLE
Separation of Concerns: Store the API service and the main component in separate files

### ISSUE THREAD

**Issue by paramsiddharth** [PragatiVerma18/Snappify#10]
# Implement separation of concerns
- Extract the screenshot API service from `App.js` and import and use it from its own module.
- Create a new component to be rendered by `App.js`, containing the main part of the application. This would ease the addition of a header/footer in future versions.

If approved, I would like to work on this issue.

**Comment by PragatiVerma18** [comment]
Go ahead @paramsiddharth!
