### ISSUE TITLE
Store API token as an environment variable

### ISSUE THREAD

**Issue by paramsiddharth** [PragatiVerma18/Snappify#21]
# Store API token as an environment variable
- The token is currently hardcoded into the source code. It would be safer to store it as an environment variable.
- Since Snappify is a React application, that would preferably be done in a `.env` file.
- The `.env` may be excluded from all future commits to ensure consistency and avoid rate-limits. Contributors may add their own API keys into a `.env` file when developing.

If approved, I would like to work on this.

**Comment by PragatiVerma18** [comment]
@paramsiddharth you can work on this!
