### ISSUE TITLE
Show the list of contributors in the readme

### ISSUE THREAD

**Issue by m-code12** [PragatiVerma18/Snappify#24]
We can add the list of contributors who contributed to this repository similar to this :

![Screenshot (294)](https://user-images.githubusercontent.com/53649201/103304639-2cc5a200-4a2f-11eb-8a6f-24270d66128c.png)

Or maybe something like [hall of fame](https://github.com/sourcerer-io/hall-of-fame/blob/develop/README.md) .

@PragatiVerma18 I would like to implement this.

**Comment by PragatiVerma18** [comment]
Go ahead @m-code12!
