### ISSUE TITLE
adding feature to get users profile screesnhot by entering password

### ISSUE THREAD

**Issue by tejaswini22199** [PragatiVerma18/Snappify#4]
When a user enters password it should give screenshot of their profile . Like Facebook or Linkedin page of one user by taking password as input.

**Comment by PragatiVerma18** [comment]
@tejaswini22199 that would require setting up OAuth through social media account APIs. That's not what we're looking for in this project, this is a very simple use case, where you enter a link(Public) and the screenshot is generated.
